services:
  spring-app:
    build: .
    container_name: spring-app

  apache:
    image: httpd:2.4
    container_name: apache-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./cert.pem:/usr/local/apache2/conf/cert.pem
      - ./key.pem:/usr/local/apache2/conf/key.pem
    depends_on:
      - spring-app
